set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-sensible'
Plugin 'bling/vim-airline'
Plugin 'derekwyatt/vim-scala'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'L9'
Plugin 'FuzzyFinder'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}

call vundle#end()            " required
filetype plugin indent on    " required

" ======================================

" Indentation
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Leader, mouse, undo-redo, swap
let mapleader=","
set mouse=a
set number
set undofile
set undodir=~/.vim/undo
set directory=~/.vim/swap

" Fuzzy Finder
let g:fuf_file_exclude = 'target'
let g:fuf_coveragefile_exclude = 'target'
map <leader>f :FufFile<CR>
map <leader>c :FufCoverageFile<CR>
map <leader>b :FufBuffer<CR>

" Solarized
set background=dark
colorscheme solarized

if has("gui_macvim")
    set guifont=Inconsolata:h14
else
    set guifont=Inconsolata
endif
